---
- name: Configure k3s
  hosts: localhost
  tasks:
    - name: Host setup
      tags:
        - setup
      block:
        - name: Install packages
          community.general.homebrew:
            name: "{{ item }}"
            state: present
          with_items:
            - argocd
            - kubectl
            - tailscale
            - terraform
            - age
            - sops
            - kustomize
            - ksops
        - name: Configure kubeconfig
          ansible.builtin.shell:
            cmd: tailscale configure kubeconfig tailscale-operator
    - name: Setup SOPS and age
      ansible.builtin.include_tasks:
        file: tasks/age.yaml
    - name: Setup git
      ansible.builtin.include_tasks:
        file: tasks/git.yaml
    - name: ArgoCD
      tags:
        - argo
      block:
        - name: Install ArgoCD
          kubernetes.core.helm:
            name: argo
            chart_repo_url: "https://argoproj.github.io/argo-helm"
            release_namespace: argocd
            create_namespace: true
            chart_ref: argo-cd
            values:
              params:
                server.insecure: true
              configs:
                cm:
                  kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"

              repoServer:
                volumes:
                  - name: custom-tools
                    emptyDir: {}

                initContainers:
                  - name: install-ksops
                    image: viaductoss/ksops:v4.3.2
                    command: ["/bin/sh", "-c"]
                    args:
                      - echo "Installing KSOPS...";
                        mv ksops /custom-tools/;
                        mv kustomize /custom-tools/;
                        echo "Done.";
                    volumeMounts:
                      - mountPath: /custom-tools
                        name: custom-tools
                volumeMounts:
                  - mountPath: /usr/local/bin/kustomize
                    name: custom-tools
                    subPath: kustomize
                  - mountPath: /usr/local/bin/ksops
                    name: custom-tools
                    subPath: ksops
                # envFrom:
                #   - secretRef:
                #       name: test

        # - name: Get definition
        #   ansible.builtin.get_url:
        #     url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        #     dest: ./argocd.yml
        #     mode: "0777"
        # - name: Install ArgoCD
        #   kubernetes.core.k8s:
        #     src: ./argocd.yml
        #     namespace: argocd
        #     state: present
        # - name: Remove definition
        #   ansible.builtin.file:
        #     path: ./argocd.yml
        #     state: absent
        # - name: Patch server configuration
        #   kubernetes.core.k8s_json_patch:
        #     kind: ConfigMap
        #     namespace: argocd
        #     name: argocd-cmd-params-cm
        #     patch:
        #       - op: add
        #         path: "/data"
        #         value: { "server.insecure": "true" }
        #   register: config_patch
        # - name: Enable Kustomize options
        #   ansible.builtin.k8s:
        #     state: present
        #     definition:
        #       apiVersion: v1
        #       kind: ConfigMap
        #       metadata:
        #         name: argocd-cm
        #         labels:
        #           app.kubernetes.io/name: argocd-cm
        #           app.kubernetes.io/part-of: argocd
        #       data:
        #         kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
        # - name: Rollout deployment
        #   shell: /bin/bash -c "kubectl rollout restart deployment argocd-server -n argocd"
        #   when: config_patch.changed
        - name: Deploy app
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: argoproj.io/v1alpha1
              kind: Application
              metadata:
                name: app-of-apps
                namespace: argocd
              spec:
                project: default
                source:
                  repoURL: https://github.com/flexwie/cluster.git
                  targetRevision: HEAD
                  path: apps/root
                destination:
                  server: https://kubernetes.default.svc
                  namespace: apps
        - name: Add ingress
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: argocd-server-ingress
                namespace: argocd
              spec:
                ingressClassName: tailscale
                defaultBackend:
                  service:
                    name: argocd-server
                    port:
                      name: http
                tls:
                  - hosts:
                      - argocd
