---
- name: Configure k3s
  hosts: localhost
  tasks:
    - name: Host setup
      tags:
        - setup
      block:
        - name: Install packages
          community.general.homebrew:
            name: "{{ item }}"
            state: present
          with_items:
            - flux
            - kubectl
            - tailscale
            - age
            - sops
            - kustomize
            - ksops
        - name: Configure kubeconfig
          ansible.builtin.shell:
            cmd: tailscale configure kubeconfig tailscale-operator
    - name: Setup SOPS and age
      ansible.builtin.include_tasks:
        file: tasks/age.yaml
    - name: Setup git
      ansible.builtin.include_tasks:
        file: tasks/git.yaml
    - name: Flux
      tags:
        - flux
      block:
        - name: Check preconditions
          ansible.builtin.command:
            cmd: flux check --pre
          failed_when: flux_pre.rc != 0
          register: flux_pre
          changed_when: true
        - name: Collect information
          block:
            - name: Get repo
              ansible.builtin.command:
                cmd: gh repo view --json name -q .name
              register: git_repo
            - name: Get owner
              ansible.builtin.command:
                cmd: gh repo view --json owner -q .owner.login
              register: git_owner
            - name: Show info
              ansible.builtin.debug:
                msg: "owner: {{git_owner.stdout}}; repo: {{git_repo.stdout}}"
        - name: Bootstrap cluster
          ansible.builtin.command:
            cmd: flux bootstrap github --owner={{git_owner.stdout}} --repository={{git_repo.stdout}} --branch=feat/flux --path=./apps --personal
