apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mariadb-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: local-path
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgqwu49ra5m5553fj747mmtzkkn5dduwrwad0l5jm934znpp9vgsxh4yd0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTjlHYW45UEZvK3p6Rkgx
            b1lDTlEzVm9EdnQxWFYyMWxrOWFZVG13eFNVCmZFT0E4SXIwTkFEM21zSmlxLzgw
            ZGh1TjhIaEFkMTIxMHNESUtwUDlMcjgKLS0tIERDcC9rcTZwcFl5RG9URURNQXB5
            cUR0NGgxczFrOVVDY1Fwc01KTlFqMmsK/tfrHd7qIhQc5V290Hl3xbfNtu4gjav/
            MwUkydvDpvMcwzoeGEi7dbL1D6er+gq2RBVP7GOvmya5pe37hWSWAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T11:22:53Z"
    mac: ENC[AES256_GCM,data:P5ENjutoBxSLtWcyPz7ZLIElzYGUHQZyH1DasMh4oCswRvuNhvi1Moe+/Ms3co2Nq+6q/qjcy3OerIIBfMDaHDkjljYn0JC2hSWpoU9V4lj8huTW6Qe1OZuW28RCdT1wDiDAaK5yRt+t01aZ3U7XjhTdEAPZ+tb7kLMB0+P0UmY=,iv:ICGL5yPD3sSRUB0Am9KmoE1qjEx/g0CkkbvPxdTN8+I=,tag:4vIr0Cv6qhHSvHt9SRVswQ==,type:str]
    pgp: []
    encrypted_regex: ^(user|password|token|secret)$
    version: 3.8.1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mariadb
spec:
    serviceName: mariadb
    replicas: 1
    selector:
        matchLabels:
            app: mariadb
    template:
        metadata:
            labels:
                app: mariadb
        spec:
            containers:
                - name: mariadb
                  image: mariadb:latest
                  env:
                    - name: MYSQL_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: mariadb_root_pwd
                            key: password
                  ports:
                    - containerPort: 3306
                      name: sql
                  volumeMounts:
                    - mountPath: /var/lib/mysql
                      name: mariadb-storage
    volumeClaimTemplates:
        - metadata:
            name: mariadb-storage
          spec:
            accessModes:
                - ReadWriteOnce
            resources:
                requests:
                    storage: 1Gi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgqwu49ra5m5553fj747mmtzkkn5dduwrwad0l5jm934znpp9vgsxh4yd0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTjlHYW45UEZvK3p6Rkgx
            b1lDTlEzVm9EdnQxWFYyMWxrOWFZVG13eFNVCmZFT0E4SXIwTkFEM21zSmlxLzgw
            ZGh1TjhIaEFkMTIxMHNESUtwUDlMcjgKLS0tIERDcC9rcTZwcFl5RG9URURNQXB5
            cUR0NGgxczFrOVVDY1Fwc01KTlFqMmsK/tfrHd7qIhQc5V290Hl3xbfNtu4gjav/
            MwUkydvDpvMcwzoeGEi7dbL1D6er+gq2RBVP7GOvmya5pe37hWSWAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T11:22:53Z"
    mac: ENC[AES256_GCM,data:P5ENjutoBxSLtWcyPz7ZLIElzYGUHQZyH1DasMh4oCswRvuNhvi1Moe+/Ms3co2Nq+6q/qjcy3OerIIBfMDaHDkjljYn0JC2hSWpoU9V4lj8huTW6Qe1OZuW28RCdT1wDiDAaK5yRt+t01aZ3U7XjhTdEAPZ+tb7kLMB0+P0UmY=,iv:ICGL5yPD3sSRUB0Am9KmoE1qjEx/g0CkkbvPxdTN8+I=,tag:4vIr0Cv6qhHSvHt9SRVswQ==,type:str]
    pgp: []
    encrypted_regex: ^(user|password|token|secret)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: mariadb_root_pwd
type: Opaque
data:
    password: ENC[AES256_GCM,data:J6xzuDaVAUg8ieD/+jBDsA==,iv:EoY5VtuNGWEiV6Tets1OyqeMvRqu4PqHNM1RtmCDzuk=,tag:a/JN9/J/W0wCvVpLIg5cRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgqwu49ra5m5553fj747mmtzkkn5dduwrwad0l5jm934znpp9vgsxh4yd0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTjlHYW45UEZvK3p6Rkgx
            b1lDTlEzVm9EdnQxWFYyMWxrOWFZVG13eFNVCmZFT0E4SXIwTkFEM21zSmlxLzgw
            ZGh1TjhIaEFkMTIxMHNESUtwUDlMcjgKLS0tIERDcC9rcTZwcFl5RG9URURNQXB5
            cUR0NGgxczFrOVVDY1Fwc01KTlFqMmsK/tfrHd7qIhQc5V290Hl3xbfNtu4gjav/
            MwUkydvDpvMcwzoeGEi7dbL1D6er+gq2RBVP7GOvmya5pe37hWSWAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T11:22:53Z"
    mac: ENC[AES256_GCM,data:P5ENjutoBxSLtWcyPz7ZLIElzYGUHQZyH1DasMh4oCswRvuNhvi1Moe+/Ms3co2Nq+6q/qjcy3OerIIBfMDaHDkjljYn0JC2hSWpoU9V4lj8huTW6Qe1OZuW28RCdT1wDiDAaK5yRt+t01aZ3U7XjhTdEAPZ+tb7kLMB0+P0UmY=,iv:ICGL5yPD3sSRUB0Am9KmoE1qjEx/g0CkkbvPxdTN8+I=,tag:4vIr0Cv6qhHSvHt9SRVswQ==,type:str]
    pgp: []
    encrypted_regex: ^(user|password|token|secret)$
    version: 3.8.1
---
apiVersion: v1
kind: Service
metadata:
    name: mariadb
    labels:
        app: mariadb
spec:
    type: ClusterIP
    selector:
        app: mariadb
    ports:
        - port: 3306
          protocol: TCP
    clusterIP: None
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jgqwu49ra5m5553fj747mmtzkkn5dduwrwad0l5jm934znpp9vgsxh4yd0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTjlHYW45UEZvK3p6Rkgx
            b1lDTlEzVm9EdnQxWFYyMWxrOWFZVG13eFNVCmZFT0E4SXIwTkFEM21zSmlxLzgw
            ZGh1TjhIaEFkMTIxMHNESUtwUDlMcjgKLS0tIERDcC9rcTZwcFl5RG9URURNQXB5
            cUR0NGgxczFrOVVDY1Fwc01KTlFqMmsK/tfrHd7qIhQc5V290Hl3xbfNtu4gjav/
            MwUkydvDpvMcwzoeGEi7dbL1D6er+gq2RBVP7GOvmya5pe37hWSWAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T11:22:53Z"
    mac: ENC[AES256_GCM,data:P5ENjutoBxSLtWcyPz7ZLIElzYGUHQZyH1DasMh4oCswRvuNhvi1Moe+/Ms3co2Nq+6q/qjcy3OerIIBfMDaHDkjljYn0JC2hSWpoU9V4lj8huTW6Qe1OZuW28RCdT1wDiDAaK5yRt+t01aZ3U7XjhTdEAPZ+tb7kLMB0+P0UmY=,iv:ICGL5yPD3sSRUB0Am9KmoE1qjEx/g0CkkbvPxdTN8+I=,tag:4vIr0Cv6qhHSvHt9SRVswQ==,type:str]
    pgp: []
    encrypted_regex: ^(user|password|token|secret)$
    version: 3.8.1
