apiVersion: apps/v1
kind: Deployment
metadata:
  name: monica
  namespace: apps
spec:
  selector:
    matchLabels:
      app: monica
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: monica
    spec:
      containers:
        - image: monica
          name: monica
          env:
            - name: DB_HOST
              value: mysql
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monice
spec:
  defaultBackend:
    service:
      name: monica
      port:
        name: https
  ingressClassName: tailscale
---
apiVersion: v1
kind: Service
metadata:
  name: monica
  namespace: apps
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: http
  selector:
    app: monica
  clusterIP: None
