apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: csi-driver-smb
    namespace: argocd
spec:
    project: default
    source:
        chart: hcloud-csi
        repoURL: https://charts.hetzner.cloud
        targetRevision: 2.7.1
    destination:
        name: in-cluster
        namespace: kube-system
    syncPolicy:
        automated: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jcg2ysz5zladh9ewwlyrurk99uw45r0k8tm2rg7p09ca6yefxq8qkyw5ac
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTTViRVpUaGtlK0o4czR4
            UWsxMnArWlJRTnlsR3RHcC9TMTZHZ01GREhjCjhqM3JZOXdJaXJISnYwcHNoVWdk
            K2JCWWJneVdjekdpb2NudHVhaGJUUTgKLS0tIGt4c0F5VGNFNlQxYlFYOTVXakVq
            MWI1QWJ2WTc2R2tsMUFlNm10OStvYVEKQhSA3i/W9f+7c6+PLXnoVOr1JFDCZLwM
            Kc/KQNL7LO7oFp3hXHoS/NAfEtlb8dAxbh5ZUDBp31CwEwSnVSDxZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T17:09:50Z"
    mac: ENC[AES256_GCM,data:Yiz1WHDBT9uZPzyfv1Q0UAyfLzBTQd376BDsaOy9vmBKBPUM94YlZUpSExKJcw2JN2rxuEudgqBzGRGjvmrJP0VzY+J2gYb085IHn1dUrOAkIB14ueDSUdf/sC5hwPCOzYhByLrlZb+GmYGlg7X3A7QA/eyXPaaFPDY1lm0oj0s=,iv:73lKAqFsJ6NreGsRidNSc/qK/9Mn3Hrgi4xZdObiY9o=,tag:TtnVEwxmeav572faovDeUw==,type:str]
    pgp: []
    encrypted_regex: ^(user|password|token|secret)$
    version: 3.8.1
