apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-smb
  namespace: argocd
spec:
  project: default
  source:
    helm:
      chart: hcloud-csi
      repoURL: https://charts.hetzner.cloud
      targetRevision: 2.7.1
  destination:
    name: "in-cluster"
    namespace: kube-system
  syncPolicy:
    automated: {}
---
apiVersion: 1
kind: Secret
metadata:
  name: hcloud
  namespace: kube-system
stringData:
  token: test
