apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: csi-driver-smb
    namespace: argocd
spec:
    project: default
    source:
        helm:
            chart: hcloud-csi
            repoURL: https://charts.hetzner.cloud
            targetRevision: 2.7.1
    destination:
        name: in-cluster
        namespace: kube-system
    syncPolicy:
        automated: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jcg2ysz5zladh9ewwlyrurk99uw45r0k8tm2rg7p09ca6yefxq8qkyw5ac
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbEFGVEN1ZDJDT0V3QXpP
            emI4UUt6UUFJM24zeHIzNm9lbjUvZWxXc0djCkxOaENlR25BMzNrN2M5UStGQmlq
            eHVyWFZSL1ZaalhMdUhpdWtaU0NUcDgKLS0tIHh2M1lmcDcrdFZjRjB0VEkxYzdM
            dUlkSyszbkpIb3NVOXY4UjRXejBWUjgKUE3NmRqiPeDD1zFgpyYEa9tsAQGR4+K8
            WC4aRiruDLgC3EhtVXkMlJVO+IPMNe1Dhj2YmLUjlSLkFK2wl6YVVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-14T12:19:42Z"
    mac: ENC[AES256_GCM,data:IKIdddaFCa+K9sRr1djuECjPgdQfXdphhQEFGPmpNjTqyf3UBL+eflYj/zFpQzwIJcgxSGwBP1yBV6FSPuP1QrgY3MQG1dPJIBRAKMDJsQKgnmIsOyqWKM/SFFuKPupqXqS4j3zyW0d6L8HRr5wDtfc1m3TjnNk1RAwXF6Wr+fk=,iv:u31+u0VPNM8emCT4m155pFT6J9mfN5Mr2t1p1NthYZk=,tag:vR7xypUoJFeW6ou/MTLO6A==,type:str]
    pgp: []
    encrypted_regex: ^(user|password|token|secret)$
    version: 3.8.1
---
apiVersion: 1
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
stringData:
    token: ENC[AES256_GCM,data:YbkREg==,iv:zw1wDxfA6cIs43ThNRuF8elNtLfU8Dk9gslemM6BPIA=,tag:eZQ7FUN7O6GzDhkInIcinA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jcg2ysz5zladh9ewwlyrurk99uw45r0k8tm2rg7p09ca6yefxq8qkyw5ac
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbEFGVEN1ZDJDT0V3QXpP
            emI4UUt6UUFJM24zeHIzNm9lbjUvZWxXc0djCkxOaENlR25BMzNrN2M5UStGQmlq
            eHVyWFZSL1ZaalhMdUhpdWtaU0NUcDgKLS0tIHh2M1lmcDcrdFZjRjB0VEkxYzdM
            dUlkSyszbkpIb3NVOXY4UjRXejBWUjgKUE3NmRqiPeDD1zFgpyYEa9tsAQGR4+K8
            WC4aRiruDLgC3EhtVXkMlJVO+IPMNe1Dhj2YmLUjlSLkFK2wl6YVVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-14T12:19:42Z"
    mac: ENC[AES256_GCM,data:IKIdddaFCa+K9sRr1djuECjPgdQfXdphhQEFGPmpNjTqyf3UBL+eflYj/zFpQzwIJcgxSGwBP1yBV6FSPuP1QrgY3MQG1dPJIBRAKMDJsQKgnmIsOyqWKM/SFFuKPupqXqS4j3zyW0d6L8HRr5wDtfc1m3TjnNk1RAwXF6Wr+fk=,iv:u31+u0VPNM8emCT4m155pFT6J9mfN5Mr2t1p1NthYZk=,tag:vR7xypUoJFeW6ou/MTLO6A==,type:str]
    pgp: []
    encrypted_regex: ^(user|password|token|secret)$
    version: 3.8.1
