apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi
  namespace: argocd
spec:
  project: default
  source:
    chart: synology-csi
    repoURL: https://christian-schlichtherle.github.io/synology-csi-chart
    targetRevision: 0.9.8
  destination:
    name: "in-cluster"
    namespace: synology-csi
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
